#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=0
change=9
while [ $counter -le 10 ]
do
 if [[ $counter == "$change" ]]
 then
   echo "Hi"
 else
   echo "Best School"
 fi
 ((counter++))
done
