#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
change1=4
change2=8
while [ $counter -le 10 ]
do
 if [[ $counter == "$change1" ]]
 then
   echo "bad luck"
 elif [[ $counter == "$change2" ]]
 then
   echo "good luck"
 else
   echo "Best School"
 fi
 ((counter++))
done
