#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
cas1=4
cas2=9
cas3=17
while [ $counter -le 10 ]
do
 if [[ $counter == "$change1" ]]
 then
   echo "bad luck"
 elif [[ $counter == "$change2" ]]
 t
 ((counter++))
done

