#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
cas1=4
cas2=9
cas3=17
while [ $counter -le 20 ]
do
  case $counter in

    $cas1)
      echo "bad luck from China"
      ;;
    $cas2)
      echo "bad luck from Japan"
      ;;
    $cas3)
      echo "bad luck from Italy"
      ;;
    *)
    echo "$counter"
    ;;
   esac
  ((counter++))
done
